function WDIInstagram(args){this.access_tokens=[];this.filters=[];if(typeof args!='undefined'){if(typeof args.access_tokens!='undefined'){this.access_tokens=args.access_tokens;}
if(typeof args.filters!='undefined'){this.filters=args.filters;}}
var _this=this;this.statusCode={429:function(){console.log(' 429: Too many requests try after one hour');},}
this.getFilter=function(methodName){var filters=_this.filters;if(typeof filters=="undefined"){return false;}
for(var i=0;i<filters.length;i++){if(filters[i].where==methodName){if(typeof filters[i].what=='object'&&filters[i].what.length==2){if(typeof window[filters[i].what[0]]!='undefined'){if(typeof window[filters[i].what[0]][filters[i].what[1]]=='function'){return window[filters[i].what[0]][filters[i].what[1]];}}}else if(typeof filters[i].what=='string'){if(typeof window[filters[i].what]=='function'){return window[filters[i].what];}}else if(typeof filters[i].what=='function'){return filters[i].what;}else{return false;}}}
return false;}
function getAccessToken(){var access_tokens=_this.access_tokens,index=parseInt(Math.random(0,1)*access_tokens.length);return access_tokens[index];}
this.addToken=function(token){if(typeof token=='string'){_this.access_tokens.push(token);}}
this.getTagRecentMedia=function(tagname,args){var instagram=this,noArgument=false,successFlag=false,statusCode=this.statusCode;errorFlag=false,argFlag=false,filter=this.getFilter('getTagRecentMedia');baseUrl='https://api.instagram.com/v1/tags/'+ tagname+'/media/recent?access_token='+ getAccessToken();if(typeof args=='undefined'||args.length===0){noArgument=true;}else{if('success'in args){successFlag=true;}
if('statusCode'in args){statusCode=args['statusCode'];}
if('error'in args){errorFlag=true;}
if('args'in args){argFlag=true;}else{args.args={};}
if('count'in args){args['count']=parseInt(args['count']);if(!Number.isInteger(args['count'])||args['count']<=0){args.count=33;}}else{args.count=33;}
baseUrl+='&count='+ args.count;if('min_tag_id'in args){baseUrl+='&min_tag_id='+ args.min_tag_id;}
if('max_tag_id'in args){baseUrl+='&max_tag_id='+ args.max_tag_id;}}
jQuery.ajax({type:'POST',url:baseUrl,dataType:'jsonp',success:function(response){if(typeof response["data"]==="undefined")response["data"]=[];if(successFlag){if(typeof args.success=='object'&&args.success.length==2){if(typeof window[args.success[0]]!='undefined'){if(typeof window[args.success[0]][args.success[1]]=='function'){if(filter){response=filter(response,instagram.filterArguments,args.args);}
window[args.success[0]][args.success[1]](response);}}}else if(typeof args.success=='string'){if(typeof window[args.success]=='function'){if(filter){response=filter(response,instagram.filterArguments,args.args);}
window[args.success](response);}}else if(typeof args.success=='function'){if(filter){response=filter(response,instagram.filterArguments,args.args);}
args.success(response);}}},error:function(response){if(errorFlag){if(typeof args['error']=='object'&&args['error'].length==2){if(typeof window[args['error'][0]][args['error'][1]]=='function'){window[args['error'][0]][args['error'][1]](response);}}else if(typeof args['error']=='string'){if(typeof window[args['error']]=='function'){window[args['error']](response);}}else if(typeof args['error']=='function'){args['error'](response);}}},statusCode:statusCode});}
this.searchForTagsByName=function(tagname,args){var instagram=this,noArgument=false,successFlag=false,statusCode=this.statusCode;errorFlag=false;filter=this.getFilter('searchForTagsByName');if(typeof args=='undefined'||args.length===0){noArgument=true;}else{if('success'in args){successFlag=true;}
if('error'in args){errorFlag=true;}
if('statusCode'in args){statusCode=args['statusCode'];}}
jQuery.ajax({type:'POST',url:'https://api.instagram.com/v1/tags/search?q='+ tagname+'&access_token='+ getAccessToken(),dataType:'jsonp',success:function(response){if(successFlag){if(typeof args.success=='object'&&args.success.length==2){if(typeof window[args.success[0]]!='undefined'){if(typeof window[args.success[0]][args.success[1]]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
window[args.success[0]][args.success[1]](response);}}}else if(typeof args.success=='string'){if(typeof window[args.success]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
window[args.success](response);}}else if(typeof args.success=='function'){if(filter){response=filter(response,instagram.filterArguments);}
args.success(response);}}},error:function(response){if(errorFlag){if(typeof args['error']=='object'&&args['error'].length==2){if(typeof window[args['error'][0]][args['error'][1]]=='function'){window[args['error'][0]][args['error'][1]](response);}}else if(typeof args['error']=='string'){if(typeof window[args['error']]=='function'){window[args['error']](response);}}else if(typeof args['error']=='function'){args['error'](response);}}},statusCode:statusCode});}
this.searchForUsersByName=function(username,args){var instagram=this,noArgument=false,successFlag=false,statusCode=this.statusCode,errorFlag=false,filter=this.getFilter('searchForUsersByName');if(typeof args=='undefined'||args.length===0){noArgument=true;}else{if('success'in args){successFlag=true;}
if('error'in args){errorFlag=true;}
if('statusCode'in args){statusCode=args['statusCode'];}}
jQuery.ajax({type:'POST',dataType:'jsonp',url:'https://api.instagram.com/v1/users/search?q='+ username+'&access_token='+ getAccessToken(),success:function(response){if(successFlag){if(typeof args.success=='object'&&args.success.length==2){if(typeof window[args.success[0]]!='undefined'){if(typeof window[args.success[0]][args.success[1]]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
response.args=args;window[args.success[0]][args.success[1]](response);}}}else if(typeof args.success=='string'){if(typeof window[args.success]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
response.args=args;window[args.success](response);}}else if(typeof args.success=='function'){if(filter){response=filter(response,instagram.filterArguments);}
response.args=args;args.success(response);}}},error:function(response){if(errorFlag){if(typeof args['error']=='object'&&args['error'].length==2){if(typeof window[args['error'][0]][args['error'][1]]=='function'){window[args['error'][0]][args['error'][1]](response);}}else if(typeof args['error']=='string'){if(typeof window[args['error']]=='function'){window[args['error']](response);}}else if(typeof args['error']=='function'){args['error'](response);}}},statusCode:this.statusCode});}
this.getRecentLikedMedia=function(args){var instagram=this,noArgument=false,successFlag=false,statusCode=this.statusCode,errorFlag=false,filter=this.getFilter('getRecentLikedMedia');if(typeof args=='undefined'||args.length===0){noArgument=true;}else{if('success'in args){successFlag=true;}
if('error'in args){errorFlag=true;}
if('statusCode'in args){statusCode=args['statusCode'];}}
jQuery.ajax({type:'POST',dataType:'jsonp',url:'https://api.instagram.com/v1/users/self/media/liked?access_token='+ getAccessToken(),success:function(response){if(successFlag){if(typeof args.success=='object'&&args.success.length==2){if(typeof window[args.success[0]]!='undefined'){if(typeof window[args.success[0]][args.success[1]]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
window[args.success[0]][args.success[1]](response);}}}else if(typeof args.success=='string'){if(typeof window[args.success]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
window[args.success](response);}}else if(typeof args.success=='function'){if(filter){response=filter(response,instagram.filterArguments);}
args.success(response);}}},error:function(response){if(errorFlag){if(typeof args['error']=='object'&&args['error'].length==2){if(typeof window[args['error'][0]][args['error'][1]]=='function'){window[args['error'][0]][args['error'][1]](response);}}else if(typeof args['error']=='string'){if(typeof window[args['error']]=='function'){window[args['error']](response);}}else if(typeof args['error']=='function'){args['error'](response);}}},statusCode:statusCode});}
this.getUserRecentMedia=function(user_id,args){var instagram=this,noArgument=false,successFlag=false,argFlag=false,statusCode=this.statusCode,errorFlag=false,filter=this.getFilter('getUserRecentMedia'),baseUrl='https://api.instagram.com/v1/users/'+ user_id+'/media/recent/?access_token='+ getAccessToken();if(typeof args=='undefined'||args.length===0){noArgument=true;}else{if('success'in args){successFlag=true;}
if('statusCode'in args){statusCode=args['statusCode'];}
if('args'in args){argFlag=true;}else{args.args={};}
if('error'in args){errorFlag=true;}
if('count'in args){args['count']=parseInt(args['count']);if(!Number.isInteger(args['count'])||args['count']<=0){args.count=33;}}else{args.count=33;}
baseUrl+='&count='+ args.count;if('min_id'in args){baseUrl+='&min_id='+ args.min_id;}
if('max_id'in args){baseUrl+='&max_id='+ args.max_id;}}
jQuery.ajax({type:'POST',dataType:'jsonp',url:baseUrl,success:function(response){if(typeof response["data"]==="undefined")response["data"]=[];if(successFlag){if(typeof args.success=='object'&&args.success.length==2){if(typeof window[args.success[0]]!='undefined'){if(typeof window[args.success[0]][args.success[1]]=='function'){if(filter){response=filter(response,instagram.filterArguments,args.args);}
window[args.success[0]][args.success[1]](response);}}}else if(typeof args.success=='string'){if(typeof window[args.success]=='function'){if(filter){response=filter(response,instagram.filterArguments,args.args);}
window[args.success](response);}}else if(typeof args.success=='function'){if(filter){response=filter(response,instagram.filterArguments,args.args);}
args.success(response);}}},error:function(response){if(errorFlag){if(typeof args['error']=='object'&&args['error'].length==2){if(typeof window[args['error'][0]][args['error'][1]]=='function'){window[args['error'][0]][args['error'][1]](response);}}else if(typeof args['error']=='string'){if(typeof window[args['error']]=='function'){window[args['error']](response);}}else if(typeof args['error']=='function'){args['error'](response);}}},statusCode:statusCode});}
this.getSelfRecentMedia=function(args){var instagram=this,noArgument=false,successFlag=false,statusCode=this.statusCode;errorFlag=false,filter=this.getFilter('getSelfRecentMedia'),baseUrl='https://api.instagram.com/v1/users/self/media/recent/?access_token='+ getAccessToken();if(typeof args=='undefined'||args.length===0){noArgument=true;}else{if('success'in args){successFlag=true;}
if('error'in args){errorFlag=true;}
if('statusCode'in args){statusCode=args['statusCode'];}
if('count'in args){args['count']=parseInt(args['count']);if(!Number.isInteger(args['count'])||args['count']<=0){args.count=33;}}else{args.count=33;}
baseUrl+='&count='+ args.count;if('min_id'in args){baseUrl+='&min_id='+ args.min_id;}
if('max_id'in args){baseUrl+='&max_id='+ args.max_id;}}
jQuery.ajax({type:'POST',dataType:'jsonp',url:baseUrl,success:function(response){if(successFlag){if(typeof args.success=='object'&&args.success.length==2){if(typeof window[args.success[0]]!='undefined'){if(typeof window[args.success[0]][args.success[1]]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
window[args.success[0]][args.success[1]](response);}}}else if(typeof args.success=='string'){if(typeof window[args.success]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
window[args.success](response);}}else if(typeof args.success=='function'){if(filter){response=filter(response,instagram.filterArguments);}
args.success(response);}}},error:function(response){if(errorFlag){if(typeof args['error']=='object'&&args['error'].length==2){if(typeof window[args['error'][0]][args['error'][1]]=='function'){window[args['error'][0]][args['error'][1]](response);}}else if(typeof args['error']=='string'){if(typeof window[args['error']]=='function'){window[args['error']](response);}}else if(typeof args['error']=='function'){args['error'](response);}}},statusCode:statusCode});}
this.getUserInfo=function(user_id,args){var instagram=this,noArgument=false,successFlag=false,statusCode=this.statusCode,errorFlag=false,filter=this.getFilter('getUserInfo');if(typeof args=='undefined'||args.length===0){noArgument=true;}else{if('success'in args){successFlag=true;}
if('error'in args){errorFlag=true;}
if('statusCode'in args){statusCode=args['statusCode'];}}
jQuery.ajax({type:'POST',dataType:'jsonp',url:'https://api.instagram.com/v1/users/'+ user_id+'/?access_token='+ getAccessToken(),success:function(response){if(successFlag){if(typeof args.success=='object'&&args.success.length==2){if(typeof window[args.success[0]]!='undefined'){if(typeof window[args.success[0]][args.success[1]]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
window[args.success[0]][args.success[1]](response);}}}else if(typeof args.success=='string'){if(typeof window[args.success]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
window[args.success](response);}}else if(typeof args.success=='function'){if(filter){response=filter(response,instagram.filterArguments);}
args.success(response);}}},error:function(response){if(errorFlag){if(typeof args['error']=='object'&&args['error'].length==2){if(typeof window[args['error'][0]][args['error'][1]]=='function'){window[args['error'][0]][args['error'][1]](response);}}else if(typeof args['error']=='string'){if(typeof window[args['error']]=='function'){window[args['error']](response);}}else if(typeof args['error']=='function'){args['error'](response);}}},statusCode:statusCode});}
this.getSelfInfo=function(args){var instagram=this,noArgument=false,successFlag=false,statusCode=this.statusCode,errorFlag=false,filter=this.getFilter('getSelfInfo');if(typeof args=='undefined'||args.length===0){noArgument=true;}else{if('success'in args){successFlag=true;}
if('error'in args){errorFlag=true;}
if('statusCode'in args){statusCode=args['statusCode'];}}
jQuery.ajax({type:'POST',dataType:'jsonp',url:'https://api.instagram.com/v1/users/self/?access_token='+ getAccessToken(),success:function(response){if(successFlag){if(typeof args.success=='object'&&args.success.length==2){if(typeof window[args.success[0]]!='undefined'){if(typeof window[args.success[0]][args.success[1]]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
window[args.success[0]][args.success[1]](response);}}}else if(typeof args.success=='string'){if(typeof window[args.success]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
window[args.success](response);}}else if(typeof args.success=='function'){if(filter){response=filter(response,instagram.filterArguments);}
args.success(response);}}},error:function(response){if(errorFlag){if(typeof args['error']=='object'&&args['error'].length==2){if(typeof window[args['error'][0]][args['error'][1]]=='function'){window[args['error'][0]][args['error'][1]](response);}}else if(typeof args['error']=='string'){if(typeof window[args['error']]=='function'){window[args['error']](response);}}else if(typeof args['error']=='function'){args['error'](response);}}},statusCode:statusCode});}
this.getRecentMediaComments=function(media_id,args){var instagram=this,noArgument=false,successFlag=false,statusCode=this.statusCode,errorFlag=false,filter=this.getFilter('getRecentMediaComments');if(typeof args=='undefined'||args.length===0){noArgument=true;}else{if('success'in args){successFlag=true;}
if('error'in args){errorFlag=true;}
if('statusCode'in args){statusCode=args['statusCode'];}}
jQuery.ajax({type:'POST',dataType:'jsonp',url:'https://api.instagram.com/v1/media/'+ media_id+'/comments?access_token='+ getAccessToken(),success:function(response){if(successFlag){if(typeof args.success=='object'&&args.success.length==2){if(typeof window[args.success[0]]!='undefined'){if(typeof window[args.success[0]][args.success[1]]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
window[args.success[0]][args.success[1]](response);}}}else if(typeof args.success=='string'){if(typeof window[args.success]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
window[args.success](response);}}else if(typeof args.success=='function'){if(filter){response=filter(response,instagram.filterArguments);}
args.success(response);}}},error:function(response){if(errorFlag){if(typeof args['error']=='object'&&args['error'].length==2){if(typeof window[args['error'][0]][args['error'][1]]=='function'){window[args['error'][0]][args['error'][1]](response);}}else if(typeof args['error']=='string'){if(typeof window[args['error']]=='function'){window[args['error']](response);}}else if(typeof args['error']=='function'){args['error'](response);}}},statusCode:statusCode});}
this.getRecentMediaLikes=function(media_id,args){var instagram=this,noArgument=false,successFlag=false,statusCode=this.statusCode,errorFlag=false,filter=this.getFilter('getRecentMediaLikes');if(typeof args=='undefined'||args.length===0){noArgument=true;}else{if('success'in args){successFlag=true;}
if('error'in args){errorFlag=true;}
if('statusCode'in args){statusCode=args['statusCode'];}}
jQuery.ajax({type:'POST',dataType:'jsonp',url:'https://api.instagram.com/v1/media/'+ media_id+'/likes?access_token='+ getAccessToken(),success:function(response){if(successFlag){if(typeof args.success=='object'&&args.success.length==2){if(typeof window[args.success[0]]!='undefined'){if(typeof window[args.success[0]][args.success[1]]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
window[args.success[0]][args.success[1]](response);}}}else if(typeof args.success=='string'){if(typeof window[args.success]=='function'){if(filter){response=filter(response,instagram.filterArguments);}
window[args.success](response);}}else if(typeof args.success=='function'){if(filter){response=filter(response,instagram.filterArguments);}
args.success(response);}}},error:function(response){if(errorFlag){if(typeof args['error']=='object'&&args['error'].length==2){if(typeof window[args['error'][0]][args['error'][1]]=='function'){window[args['error'][0]][args['error'][1]](response);}}else if(typeof args['error']=='string'){if(typeof window[args['error']]=='function'){window[args['error']](response);}}else if(typeof args['error']=='function'){args['error'](response);}}},statusCode:statusCode});}
this.requestByUrl=function(requestUrl,args){var instagram=this,noArgument=false,successFlag=false,errorFlag=false,argFlag=false,statusCode=this.statusCode,filter=this.getFilter('requestByUrl'),urlParts,urlPart;urlParts=requestUrl.split('?')[1].split('&');for(var i=0;i<urlParts.length;i++){urlParts[i]=urlParts[i].split('=');if(urlParts[i][0]=='access_token'){urlParts[i][1]=getAccessToken();}
urlParts[i]=urlParts[i].join('=');}
urlParts=urlParts.join('&');requestUrl=requestUrl.split('?')[0]+'?'+ urlParts;if(typeof args=='undefined'||args.length===0){noArgument=true;}else{if('success'in args){successFlag=true;}
if('args'in args){argFlag=true;}else{args.args={};}
if('error'in args){errorFlag=true;}
if('statusCode'in args){statusCode=args['statusCode'];}}
jQuery.ajax({type:'POST',dataType:'jsonp',url:requestUrl,success:function(response){if(successFlag){if(typeof args.success=='object'&&args.success.length==2){if(typeof window[args.success[0]]!='undefined'){if(typeof window[args.success[0]][args.success[1]]=='function'){if(filter){response=filter(response,instagram.filterArguments,args.args);}
window[args.success[0]][args.success[1]](response);}}}else if(typeof args.success=='string'){if(typeof window[args.success]=='function'){if(filter){response=filter(response,instagram.filterArguments,args.args);}
window[args.success](response);}}else if(typeof args.success=='function'){if(filter){response=filter(response,instagram.filterArguments,args.args);}
args.success(response);}}},error:function(response){if(errorFlag){if(typeof args['error']=='object'&&args['error'].length==2){if(typeof window[args['error'][0]][args['error'][1]]=='function'){window[args['error'][0]][args['error'][1]](response);}}else if(typeof args['error']=='string'){if(typeof window[args['error']]=='function'){window[args['error']](response);}}else if(typeof args['error']=='function'){args['error'](response);}}},statusCode:statusCode});}}